version: "3"
services:
    nats:
        image: gitlab.lrz.de:5005/vss/misc/example-microservices/dependency/nats
    redis:
        image: gitlab.lrz.de:5005/vss/misc/example-microservices/dependency/redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    logger:
        image: gitlab.lrz.de:5005/vss/semester/ob-23ss/blatt-2/blatt2-grp06/microservices/service/logger
        build:
            dockerfile: docker/Dockerfile.logger
            context: .
        depends_on:
            - nats
            - redis
        command: -nats nats:4222 -redis redis:6379
