// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: microservices/api/supplierApi/supplierApi.proto

package supplierApi

import (
	types "gitlab.lrz.de/vss/semester/ob-23ss/blatt-2/blatt2-grp06/microservices/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSupplierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supplier *types.Supplier `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
}

func (x *AddSupplierRequest) Reset() {
	*x = AddSupplierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSupplierRequest) ProtoMessage() {}

func (x *AddSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSupplierRequest.ProtoReflect.Descriptor instead.
func (*AddSupplierRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{0}
}

func (x *AddSupplierRequest) GetSupplier() *types.Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type AddSupplierReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32 `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
}

func (x *AddSupplierReply) Reset() {
	*x = AddSupplierReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSupplierReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSupplierReply) ProtoMessage() {}

func (x *AddSupplierReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSupplierReply.ProtoReflect.Descriptor instead.
func (*AddSupplierReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{1}
}

func (x *AddSupplierReply) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type GetSupplierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32 `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
}

func (x *GetSupplierRequest) Reset() {
	*x = GetSupplierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierRequest) ProtoMessage() {}

func (x *GetSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{2}
}

func (x *GetSupplierRequest) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type GetSupplierReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supplier *types.Supplier `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
}

func (x *GetSupplierReply) Reset() {
	*x = GetSupplierReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSupplierReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierReply) ProtoMessage() {}

func (x *GetSupplierReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierReply.ProtoReflect.Descriptor instead.
func (*GetSupplierReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{3}
}

func (x *GetSupplierReply) GetSupplier() *types.Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type RemoveSupplierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32 `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
}

func (x *RemoveSupplierRequest) Reset() {
	*x = RemoveSupplierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSupplierRequest) ProtoMessage() {}

func (x *RemoveSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSupplierRequest.ProtoReflect.Descriptor instead.
func (*RemoveSupplierRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSupplierRequest) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

type RemoveSupplierReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supplier *types.Supplier `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
}

func (x *RemoveSupplierReply) Reset() {
	*x = RemoveSupplierReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSupplierReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSupplierReply) ProtoMessage() {}

func (x *RemoveSupplierReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSupplierReply.ProtoReflect.Descriptor instead.
func (*RemoveSupplierReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSupplierReply) GetSupplier() *types.Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type AddProductsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32   `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	Products   []uint32 `protobuf:"varint,2,rep,packed,name=products,proto3" json:"products,omitempty"`
}

func (x *AddProductsRequest) Reset() {
	*x = AddProductsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsRequest) ProtoMessage() {}

func (x *AddProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsRequest.ProtoReflect.Descriptor instead.
func (*AddProductsRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{6}
}

func (x *AddProductsRequest) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *AddProductsRequest) GetProducts() []uint32 {
	if x != nil {
		return x.Products
	}
	return nil
}

type AddProductsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supplier *types.Supplier `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
}

func (x *AddProductsReply) Reset() {
	*x = AddProductsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsReply) ProtoMessage() {}

func (x *AddProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsReply.ProtoReflect.Descriptor instead.
func (*AddProductsReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{7}
}

func (x *AddProductsReply) GetSupplier() *types.Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type RemoveProductsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32   `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	Products   []uint32 `protobuf:"varint,2,rep,packed,name=products,proto3" json:"products,omitempty"`
}

func (x *RemoveProductsRequest) Reset() {
	*x = RemoveProductsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProductsRequest) ProtoMessage() {}

func (x *RemoveProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProductsRequest.ProtoReflect.Descriptor instead.
func (*RemoveProductsRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveProductsRequest) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *RemoveProductsRequest) GetProducts() []uint32 {
	if x != nil {
		return x.Products
	}
	return nil
}

type RemoveProductsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Supplier *types.Supplier `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
}

func (x *RemoveProductsReply) Reset() {
	*x = RemoveProductsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProductsReply) ProtoMessage() {}

func (x *RemoveProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProductsReply.ProtoReflect.Descriptor instead.
func (*RemoveProductsReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveProductsReply) GetSupplier() *types.Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type OrderProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupplierId uint32 `protobuf:"varint,1,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	ProductId  uint32 `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount     uint32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OrderProductRequest) Reset() {
	*x = OrderProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductRequest) ProtoMessage() {}

func (x *OrderProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductRequest.ProtoReflect.Descriptor instead.
func (*OrderProductRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{10}
}

func (x *OrderProductRequest) GetSupplierId() uint32 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *OrderProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProductRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type OrderProductReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId uint32 `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Amount    uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *OrderProductReply) Reset() {
	*x = OrderProductReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductReply) ProtoMessage() {}

func (x *OrderProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_supplierApi_supplierApi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductReply.ProtoReflect.Descriptor instead.
func (*OrderProductReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP(), []int{11}
}

func (x *OrderProductReply) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderProductReply) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_microservices_api_supplierApi_supplierApi_proto protoreflect.FileDescriptor

var file_microservices_api_supplierApi_supplierApi_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2f,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x70, 0x69, 0x1a, 0x23,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x75, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x08, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x53, 0x75, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x22, 0x37, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x52, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x50,
	0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73,
	0x22, 0x3f, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x22, 0x53, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x42, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a,
	0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x52, 0x08, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x6b, 0x0a, 0x13, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x72, 0x7a,
	0x2e, 0x64, 0x65, 0x2f, 0x76, 0x73, 0x73, 0x2f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72,
	0x2f, 0x6f, 0x62, 0x2d, 0x32, 0x33, 0x73, 0x73, 0x2f, 0x62, 0x6c, 0x61, 0x74, 0x74, 0x2d, 0x32,
	0x2f, 0x62, 0x6c, 0x61, 0x74, 0x74, 0x32, 0x2d, 0x67, 0x72, 0x70, 0x30, 0x36, 0x2f, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_microservices_api_supplierApi_supplierApi_proto_rawDescOnce sync.Once
	file_microservices_api_supplierApi_supplierApi_proto_rawDescData = file_microservices_api_supplierApi_supplierApi_proto_rawDesc
)

func file_microservices_api_supplierApi_supplierApi_proto_rawDescGZIP() []byte {
	file_microservices_api_supplierApi_supplierApi_proto_rawDescOnce.Do(func() {
		file_microservices_api_supplierApi_supplierApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_microservices_api_supplierApi_supplierApi_proto_rawDescData)
	})
	return file_microservices_api_supplierApi_supplierApi_proto_rawDescData
}

var file_microservices_api_supplierApi_supplierApi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_microservices_api_supplierApi_supplierApi_proto_goTypes = []interface{}{
	(*AddSupplierRequest)(nil),    // 0: supplierApi.AddSupplierRequest
	(*AddSupplierReply)(nil),      // 1: supplierApi.AddSupplierReply
	(*GetSupplierRequest)(nil),    // 2: supplierApi.GetSupplierRequest
	(*GetSupplierReply)(nil),      // 3: supplierApi.GetSupplierReply
	(*RemoveSupplierRequest)(nil), // 4: supplierApi.RemoveSupplierRequest
	(*RemoveSupplierReply)(nil),   // 5: supplierApi.RemoveSupplierReply
	(*AddProductsRequest)(nil),    // 6: supplierApi.AddProductsRequest
	(*AddProductsReply)(nil),      // 7: supplierApi.AddProductsReply
	(*RemoveProductsRequest)(nil), // 8: supplierApi.RemoveProductsRequest
	(*RemoveProductsReply)(nil),   // 9: supplierApi.RemoveProductsReply
	(*OrderProductRequest)(nil),   // 10: supplierApi.OrderProductRequest
	(*OrderProductReply)(nil),     // 11: supplierApi.OrderProductReply
	(*types.Supplier)(nil),        // 12: types.Supplier
}
var file_microservices_api_supplierApi_supplierApi_proto_depIdxs = []int32{
	12, // 0: supplierApi.AddSupplierRequest.supplier:type_name -> types.Supplier
	12, // 1: supplierApi.GetSupplierReply.supplier:type_name -> types.Supplier
	12, // 2: supplierApi.RemoveSupplierReply.supplier:type_name -> types.Supplier
	12, // 3: supplierApi.AddProductsReply.supplier:type_name -> types.Supplier
	12, // 4: supplierApi.RemoveProductsReply.supplier:type_name -> types.Supplier
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_microservices_api_supplierApi_supplierApi_proto_init() }
func file_microservices_api_supplierApi_supplierApi_proto_init() {
	if File_microservices_api_supplierApi_supplierApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSupplierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSupplierReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSupplierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSupplierReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSupplierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSupplierReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddProductsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveProductsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveProductsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_supplierApi_supplierApi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderProductReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microservices_api_supplierApi_supplierApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_microservices_api_supplierApi_supplierApi_proto_goTypes,
		DependencyIndexes: file_microservices_api_supplierApi_supplierApi_proto_depIdxs,
		MessageInfos:      file_microservices_api_supplierApi_supplierApi_proto_msgTypes,
	}.Build()
	File_microservices_api_supplierApi_supplierApi_proto = out.File
	file_microservices_api_supplierApi_supplierApi_proto_rawDesc = nil
	file_microservices_api_supplierApi_supplierApi_proto_goTypes = nil
	file_microservices_api_supplierApi_supplierApi_proto_depIdxs = nil
}
