// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: microservices/api/customerApi/customerApi.proto

package customerApi

import (
	types "gitlab.lrz.de/vss/semester/ob-23ss/blatt-2/blatt2-grp06/microservices/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer *types.Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
}

func (x *AddCustomerRequest) Reset() {
	*x = AddCustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerRequest) ProtoMessage() {}

func (x *AddCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerRequest.ProtoReflect.Descriptor instead.
func (*AddCustomerRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{0}
}

func (x *AddCustomerRequest) GetCustomer() *types.Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type AddCustomerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId uint32 `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *AddCustomerReply) Reset() {
	*x = AddCustomerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerReply) ProtoMessage() {}

func (x *AddCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerReply.ProtoReflect.Descriptor instead.
func (*AddCustomerReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{1}
}

func (x *AddCustomerReply) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId uint32 `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{2}
}

func (x *GetCustomerRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetCustomerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer *types.Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
}

func (x *GetCustomerReply) Reset() {
	*x = GetCustomerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerReply) ProtoMessage() {}

func (x *GetCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerReply.ProtoReflect.Descriptor instead.
func (*GetCustomerReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomerReply) GetCustomer() *types.Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type RemoveCustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId uint32 `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
}

func (x *RemoveCustomerRequest) Reset() {
	*x = RemoveCustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCustomerRequest) ProtoMessage() {}

func (x *RemoveCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCustomerRequest.ProtoReflect.Descriptor instead.
func (*RemoveCustomerRequest) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCustomerRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type RemoveCustomerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer *types.Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
}

func (x *RemoveCustomerReply) Reset() {
	*x = RemoveCustomerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCustomerReply) ProtoMessage() {}

func (x *RemoveCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_microservices_api_customerApi_customerApi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCustomerReply.ProtoReflect.Descriptor instead.
func (*RemoveCustomerReply) Descriptor() ([]byte, []int) {
	return file_microservices_api_customerApi_customerApi_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveCustomerReply) GetCustomer() *types.Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

var File_microservices_api_customerApi_customerApi_proto protoreflect.FileDescriptor

var file_microservices_api_customerApi_customerApi_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2f,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x70, 0x69, 0x1a, 0x23,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x22, 0x37, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x13, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x42, 0x57,
	0x5a, 0x55, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6c, 0x72, 0x7a, 0x2e, 0x64, 0x65, 0x2f,
	0x76, 0x73, 0x73, 0x2f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x62, 0x2d,
	0x32, 0x33, 0x73, 0x73, 0x2f, 0x62, 0x6c, 0x61, 0x74, 0x74, 0x2d, 0x32, 0x2f, 0x62, 0x6c, 0x61,
	0x74, 0x74, 0x32, 0x2d, 0x67, 0x72, 0x70, 0x30, 0x36, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_microservices_api_customerApi_customerApi_proto_rawDescOnce sync.Once
	file_microservices_api_customerApi_customerApi_proto_rawDescData = file_microservices_api_customerApi_customerApi_proto_rawDesc
)

func file_microservices_api_customerApi_customerApi_proto_rawDescGZIP() []byte {
	file_microservices_api_customerApi_customerApi_proto_rawDescOnce.Do(func() {
		file_microservices_api_customerApi_customerApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_microservices_api_customerApi_customerApi_proto_rawDescData)
	})
	return file_microservices_api_customerApi_customerApi_proto_rawDescData
}

var file_microservices_api_customerApi_customerApi_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_microservices_api_customerApi_customerApi_proto_goTypes = []interface{}{
	(*AddCustomerRequest)(nil),    // 0: customerApi.AddCustomerRequest
	(*AddCustomerReply)(nil),      // 1: customerApi.AddCustomerReply
	(*GetCustomerRequest)(nil),    // 2: customerApi.GetCustomerRequest
	(*GetCustomerReply)(nil),      // 3: customerApi.GetCustomerReply
	(*RemoveCustomerRequest)(nil), // 4: customerApi.RemoveCustomerRequest
	(*RemoveCustomerReply)(nil),   // 5: customerApi.RemoveCustomerReply
	(*types.Customer)(nil),        // 6: types.Customer
}
var file_microservices_api_customerApi_customerApi_proto_depIdxs = []int32{
	6, // 0: customerApi.AddCustomerRequest.customer:type_name -> types.Customer
	6, // 1: customerApi.GetCustomerReply.customer:type_name -> types.Customer
	6, // 2: customerApi.RemoveCustomerReply.customer:type_name -> types.Customer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_microservices_api_customerApi_customerApi_proto_init() }
func file_microservices_api_customerApi_customerApi_proto_init() {
	if File_microservices_api_customerApi_customerApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microservices_api_customerApi_customerApi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_customerApi_customerApi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCustomerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_customerApi_customerApi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_customerApi_customerApi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCustomerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_customerApi_customerApi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microservices_api_customerApi_customerApi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCustomerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microservices_api_customerApi_customerApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_microservices_api_customerApi_customerApi_proto_goTypes,
		DependencyIndexes: file_microservices_api_customerApi_customerApi_proto_depIdxs,
		MessageInfos:      file_microservices_api_customerApi_customerApi_proto_msgTypes,
	}.Build()
	File_microservices_api_customerApi_customerApi_proto = out.File
	file_microservices_api_customerApi_customerApi_proto_rawDesc = nil
	file_microservices_api_customerApi_customerApi_proto_goTypes = nil
	file_microservices_api_customerApi_customerApi_proto_depIdxs = nil
}
