version: "3"

services:
    redis:
        image: redis:alpine
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - 6379:6379

    nats:
        image: nats
        ports:
            - 4222:4222
